-- BASIC LEVEL SQL SOLUTIONS (1–15)
-- 1.Total number of customers 
SELECT COUNT(*) AS total_customers FROM customers;

-- 2.Total number of order place 
SELECT COUNT(*) AS total_orders FROM orders;

-- 3. List all product with price > 5000
SELECT product_id, product_name, price FROM Products
WHERE price > 5000;

-- 4 Show all customers from maharashtra
SELECT * FROM customers WHERE state = 'Maharashtra';

-- 5.Find all orders that are cancelled

SELECT * FROM orders 
WHERE order_status = 'Cancelled';

-- 6.Count number of products in each category

SELECT 
    c.category_name,
    COUNT(p.product_id) AS total_products
FROM products p
JOIN category c
    ON p.category_id = c.category_id
GROUP BY c.category_name;

-- 7.Total revenue generated
SELECT 
    SUM(quantity * price_per_unit) AS total_revenue
FROM order_items;

-- 8.Top 10 most expensive products

SELECT product_id, product_name, price
FROM products
ORDER BY price DESC
LIMIT 10;

-- 9. Total number of seller 
SELECT COUNT(*) AS total_sellers
FROM sellers

-- 10. Orders Placed in july 2024

SELECT * FROM orders
WHERE order_date BETWEEN '2024-07-01' AND '2024-07-31';

-- 11. Find all returens orders
SELECT * FROM orders
WHERE order_status = 'returned';

-- 12. Total quantity sold for each product

SELECT 
    product_id,
    SUM(quantity) AS total_quantity_sold 
FROM order_items
GROUP BY product_id;

-- 13.Average product price per category

SELECT 
  c.category_name,
  AVG(p.price) AS avg_price
FROM products p 
JOIN category c
    ON p.category_id = c.category_id
GROUP BY c.category_name;	
	
-- 14.LIst all payments that are pending
SELECT * FROM payments
WHERE payment_status = 'Pending';

-- 15.Show products with stock less than 50
SELECT 
   p.product_id,
   p.product_name,
   i.stock
FROM inventory i 
JOIN products p 
ON i.product_id = p.product_id
WHERE i.stock < 50;
   
-- INTERMEDIATE LEVEL SQL SOLUTIONS  
-- 16.Total revenue per category

SELECT 
   c.category_name,
   SUM(oi.quantity * oi.price_per_unit) AS revenue
FROM order_items oi
JOIN products p 
ON oi.product_id = p.product_id
JOIN category c 
ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY revenue DESC;
	
-- 17.Top 5 customers by total spending 
SELECT 
   c.customer_id,
   c.first_name,
   c.last_name,
   SUM(oi.quantity * oi.price_per_unit) AS total_spent 
   FROM customers c
   JOIN orders o 
   ON c.customer_id = o.customer_id
   JOIN order_items oi 
   ON o.order_id = oi.order_id
   GROUP BY c.customer_id, c.first_name, c.last_name
   ORDER BY total_spent DESC
   LIMIT 5;
   
-- 18.Top 5 customers by total spending 
SELECT 
    c.customer_id,
    c.first_name,
    c.last_name,
    SUM(oi.quantity * oi.price_per_unit) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_spent DESC
LIMIT 5;

-- 19.Revenue generated by each seller 
SELECT 
   s.seller_name,
   SUM(oi.quantity * oi.price_per_unit) AS revenue
FROM sellers s 
JOIN orders o 
ON s.seller_id = o.seller_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY s.seller_name
ORDER BY revenue DESC;

-- 20.Average order value (AOV)
SELECT 
   SUM(oi.quantity * oi.price_per_unit) 
   / COUNT(DISTINCT oi.order_id) AS avg_order_value
FROM order_items oi;   
   
-- 21.Number of orders per state
SELECT 
   c.state,
   COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.state
ORDER BY total_orders DESC;

-- 22. Customer who placed the highest number of orders 

SELECT 
   c.customer_id,
   c.first_name,
   c.last_name,
   COUNT(o.order_id) AS order_count
FROM customers c  
JOIN orders o 
ON o.customer_id = c. customer_id 
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY order_count DESC
LIMIT 5;

SELECT
    SUM(quantity * price_per_unit) AS total,
    COUNT(DISTINCT order_id) AS total_orders,
    AVG(quantity * price_per_unit) AS average,
    MIN(quantity * price_per_unit) AS lowest,
    MAX(quantity * price_per_unit) AS highest
FROM order_items;

-- 23.Most popular category 
SELECT 
   c.category_name,
   SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN products p 
ON oi.product_id = p.product_id
JOIN category c 
ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY total_sold DESC
LIMIT 2 ;

-- 24.Orders that have not been shipped 
SELECT o.*
FROM orders o 
LEFT JOIN shipping s 
    ON o.order_id = s.order_id 
WHERE s.order_id IS NULL;	

SELECT *
FROM orders
WHERE order_status NOT IN ('shipped', 'completed');

SELECT *
FROM orders
WHERE order_status = 'cancelled';

-- 25.Products that were never ordered
SELECT p.product_id, p.product_name
FROM products p
LEFT JOIN order_items oi
ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;

-- 26.Customers who never placed any order
SELECT 
    c.customer_id,
	c.first_name,
	c.last_name
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL;

-- 27.Revenue per month
SELECT 
   DATE_TRUNC('month', o.order_date) AS month,
   SUM(oi.quantity * oi.price_per_unit) AS revenue
FROM orders o
JOIN order_items oi 
ON o.order_id = oi.order_id
GROUP BY month
ORDER BY month;

-- 28.Top 3 sellers by revenue

SELECT 
    s.seller_name,
    SUM(oi.quantity * oi.price_per_unit) AS revenue
FROM sellers s
JOIN orders o ON s.seller_id = o.seller_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY s.seller_name
ORDER BY revenue DESC
LIMIT 3;

-- 29.Average delivery time per shipping provider

SELECT 
   shipping_provider,
   AVG(return_date - shipping_date) AS avg_days
FROM shipping
WHERE return_date IS NOT NULL
GROUP BY shipping_provider;
	
-- 30.Orders delivered late (more than 7 days)  
SELECT * 
FROM shipping
WHERE return_date IS NOT NULL
AND (return_date - shipping_date) > 7;

-- 31.Return rate per category

SELECT 
    c.category_name,
	COUNT(CASE WHEN s.delivery_status = 'Returned' THEN 1 END) * 100.0
	/ COUNT(*) AS return_rate
FROM orders o
JOIN shipping s ON o.order_id = s.order_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id 
JOIN Category c ON p.category_id = c.category_id 
GROUP BY c.category_name;
	
-- 32.Payment success rate 
SELECT 
   COUNT(CASE WHEN payment_status = 'Paid' THEN 1 END) * 100.0
   /COUNT(*) AS success_rate
FROM payments;   

-- 33.Most returned products
SELECT 
    p.product_name,
	COUNT(*) AS return_count
FROM shipping s 
JOIN orders o ON s.order_id = o.order_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
WHERE s.delivery_status = 'Returned'
GROUP BY p.product_name
ORDER BY return_count DESC
LIMIT 5;

-- 34.Top 10 Customers by order frequency

SELECT 
    c.customer_id,
	c.first_name,
	c.last_name,
	COUNT(order_id) AS total_order
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_order DESC
LIMIT 10;
    
-- 35.Products with highest profit margin

SELECT 
   p.product_name,
   (price - cogs) AS profit_margin
FROM products p
ORDER BY profit_margin DESC
LIMIT 5;

-- 36.Revenue contribution of each category(%)

SELECT 
   c.category_name,
   SUM(oi.quantity * oi.price_per_unit) * 100 /
   SUM(SUM(oi.quantity * oi.price_per_unit)) OVER()
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN category c ON p.category_id = c.category_id
GROUP BY c.category_name;
  
-- 37.Find repeat customers (more than 1 order)

SELECT 
    customer_id,
	COUNT(order_id) AS order_count 
FROM orders 
GROUP BY customer_id
HAVING COUNT(order_id) >1;
	
-- 38.Find first order date for each customer 
SELECT 
   customer_id,
   MIN(order_date) AS first_order_date
FROM orders  
GROUP BY customer_id;

-- 39.Average quantity per order 

SELECT
   AVG(total_qty) AS avg_quantity_per_order
FROM (
   SELECT 
      order_id,
	  SUM(quantity) AS total_qty
   FROM order_items
   GROUP BY order_id
)sub;   

-- 40.Most active state by revenue

SELECT
    c.state,
	SUM(oi.quantity * oi.price_per_unit) AS revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.state
ORDER BY revenue DESC
LIMIT 1;

-- ADVANCED SQL SOLUTIONS (41–70)

-- 41.Customer lifetime Value ()
-- Customer lifetime Value (CLV)
SELECT 
   c.customer_id,
   c.first_name,
   c.last_name,
   SUM(oi.quantity * oi.price_per_unit) AS lifetime_value
FROM customers c 
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY lifetime_value DESC;

-- 42.Top 10 customers by CLV
SELECT * 
FROM (
   SELECT 
      c.customer_id,
	  c.first_name,
	  c.last_name,
	SUM(oi.quantity * oi.price_per_unit) AS lifetime_value
	FROM customers c
	JOIN orders o ON c.customer_id = o.customer_id
	JOIN order_items oi ON o.order_id = oi.order_id 
	GROUP BY c.customer_id, c.first_name, c.last_name
)
    ORDER BY lifetime_value
	LIMIT 10;

-- 43.Monthly active customers 
SELECT 
   DATE_TRUNC('month', order_date) AS month,
   COUNT(DISTINCT customer_id) AS active_customers
FROM orders 
GROUP BY month
ORDER BY month;

-- 44.Customer retension rate 
WITH first_month AS (
    SELECT 
        customer_id,
        MIN(DATE_TRUNC('month', order_date)) AS first_order_month
    FROM orders
    GROUP BY customer_id
),
repeat_customers AS (
    SELECT DISTINCT o.customer_id
    FROM orders o
    JOIN first_month f
        ON o.customer_id = f.customer_id
    WHERE DATE_TRUNC('month', o.order_date) > f.first_order_month
)
SELECT 
    COUNT(DISTINCT r.customer_id) * 100.0 /
    COUNT(DISTINCT f.customer_id) AS retention_rate
FROM first_month f
LEFT JOIN repeat_customers r
ON f.customer_id = r.customer_id;

-- 45. Churned customers (no orders in last 90 days)

SELECT 
    customer_id
FROM orders
GROUP BY customer_id
HAVING MAX(order_date) < CURRENT_DATE - INTERVAL '90 days';

-- 46. Customer cohort analysis (by first purchase month)
WITH cohort AS (
    SELECT 
        customer_id,
        MIN(DATE_TRUNC('month', order_date)) AS cohort_month
    FROM orders
    GROUP BY customer_id
)
SELECT 
    cohort_month,
    COUNT(customer_id) AS customers
FROM cohort
GROUP BY cohort_month
ORDER BY cohort_month;

-- Revenue & Profit Analysis
-- 47. Monthly revenue growth rate
WITH monthly_revenue AS (
    SELECT 
        DATE_TRUNC('month', o.order_date) AS month,
        SUM(oi.quantity * oi.price_per_unit) AS revenue
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY month
)
SELECT 
    month,
    revenue,
    LAG(revenue) OVER (ORDER BY month) AS prev_month,
    (revenue - LAG(revenue) OVER (ORDER BY month)) * 100.0
    / LAG(revenue) OVER (ORDER BY month) AS growth_rate
FROM monthly_revenue;

-- 48. Category-wise profit
SELECT 
    c.category_name,
    SUM((p.price - p.cogs) * oi.quantity) AS profit
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN category c ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY profit DESC;

-- 49. Top 5 most profitable products
SELECT 
    p.product_name,
    SUM((p.price - p.cogs) * oi.quantity) AS profit
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY profit DESC
LIMIT 5;

-- 50. Profit per seller
SELECT 
    s.seller_name,
    SUM((p.price - p.cogs) * oi.quantity) AS profit
FROM sellers s
JOIN orders o ON s.seller_id = o.seller_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
GROUP BY s.seller_name
ORDER BY profit DESC;

-- 51.Running total revenue over time 
SELECT 
    order_date,
	SUM(daily_revenue) OVER (ORDER BY order_date) AS running_total
FROM (
   SELECT 
       o.order_date,
	   SUM(oi.quantity * oi.price_per_unit) AS daily_revenue
	   FROM orders o
	   JOIN order_items oi ON o.order_id = oi.order_id
	   GROUP BY o.order_date 
)t;	

-- Order Behavior
-- 52. Average time between customer orders

SELECT 
   customer_id,
   AVG(order_gap) AS avg_days_between_orders
FROM (
   SELECT 
      customer_id, 
	  order_date - LAG(order_date)
	  OVER (PARTITION BY customer_id ORDER BY order_date) AS order_gap
	FROM orders  
)t
WHERE order_gap IS NOT NULL
GROUP BY customer_id;

-- 53. Customers who increased spending over time

WITH monthly_spend AS (
    SELECT 
	 customer_id,
	 DATE_TRUNC('month', order_date) AS month,
	 SUM(oi.quantity * oi.price_per_unit) AS spend
	 FROM orders o
	 JOIN order_items oi ON o.order_id = oi.order_id
	 GROUP BY customer_id, month
)
SELECT *
FROM monthly_spend;

-- 54.Orders with unually high value(top 5%)

SELECT * FROM(
   SELECT 
    o.order_id,
	SUM(oi.quantity * price_per_unit) order_value,
	NTILE(20) OVER (ORDER BY SUM(oi.quantity * oi.price_per_unit) DESC) AS bucket
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.order_id 
)t
WHERE bucket = 1;

-- 55. Peak order day of the week

SELECT 
    TO_CHAR(order_date, 'Day') AS day,
	COUNT(*) AS total_orders
FROM orders 
GROUP BY day
ORDER BY total_orders DESC
LIMIT 1 ;

-- Shipping & Delivery
-- 56. Average shipping time

SELECT 
   AVG(return_date - shipping_date) AS avg_shipping_days
FROM shipping
WHERE return_date IS NOT NULL;

-- 57. Shipping provider with fastest delivery
SELECT 
   shipping_provider,
   AVG(return_date - shipping_date) AS avg_days
FROM shipping
WHERE return_date IS NOT NULL
GROUP BY shipping_provider
ORDER BY avg_days
LIMIT 5;

-- 58. Return rate by shipping provider
SELECT
   shipping_provider,
   COUNT(CASE WHEN delivery_status = 'Returned' THEN 1 END) * 100.0
   / COUNT(*) AS return_rate
FROM shipping
GROUP BY shipping_provider;

-- 59.Orders delivered on the same day
SELECT * 
FROM shipping
WHERE shipping_date = return_date;

-- Inventory & Supply Chain
-- 60. Products that are out of stock
SELECT 
    p.product_name
FROM inventory i
JOIN products p ON i.product_id = p.product_id
WHERE i.stock = 0;

-- 61. Top 10 products with highest stock
SELECT 
    p.product_name,
    i.stock
FROM inventory i
JOIN products p ON i.product_id = p.product_id
ORDER BY i.stock DESC
LIMIT 10;

-- 62. Inventory turnover rate
SELECT 
    p.product_name,
    SUM(oi.quantity) / AVG(i.stock) AS turnover_rate
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN inventory i ON p.product_id = i.product_id
GROUP BY p.product_name;

-- 63. Products needing restock (high sales, low stock)
SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_sold,
    i.stock
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN inventory i ON p.product_id = i.product_id
GROUP BY p.product_name, i.stock
HAVING SUM(oi.quantity) > 100
AND i.stock < 50;

-- Window Function Problems
-- 64. Rank products by revenue within each category
SELECT 
    category_name,
    product_name,
    revenue,
    RANK() OVER (PARTITION BY category_name ORDER BY revenue DESC) AS rank
FROM (
    SELECT 
        c.category_name,
        p.product_name,
        SUM(oi.quantity * oi.price_per_unit) AS revenue
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    JOIN category c ON p.category_id = c.category_id
    GROUP BY c.category_name, p.product_name
) t;

-- 65. Top product per category
SELECT *
FROM (
    SELECT 
        c.category_name,
        p.product_name,
        SUM(oi.quantity * oi.price_per_unit) AS revenue,
        RANK() OVER (
            PARTITION BY c.category_name
            ORDER BY SUM(oi.quantity * oi.price_per_unit) DESC
        ) AS rnk
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    JOIN category c ON p.category_id = c.category_id
    GROUP BY c.category_name, p.product_name
) t
WHERE rnk = 1;

-- 66. Running total orders per customer
SELECT 
    customer_id,
    order_date,
    COUNT(order_id) OVER (
        PARTITION BY customer_id
        ORDER BY order_date
    ) AS running_orders
FROM orders;

-- 67. Revenue contribution of each order
SELECT 
    order_id,
    order_value,
    order_value * 100.0 / SUM(order_value) OVER() AS revenue_percent
FROM (
    SELECT 
        order_id,
        SUM(quantity * price_per_unit) AS order_value
    FROM order_items
    GROUP BY order_id
) t;

-- 68. Top 3 orders per customer
SELECT *
FROM (
    SELECT 
        customer_id,
        order_id,
        SUM(oi.quantity * oi.price_per_unit) AS order_value,
        RANK() OVER (
            PARTITION BY customer_id
            ORDER BY SUM(oi.quantity * oi.price_per_unit) DESC
        ) AS rnk
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY customer_id, order_id
) t
WHERE rnk <= 3;

-- Business KPI Queries
-- 69. KPI summary
SELECT
    (SELECT SUM(quantity * price_per_unit) FROM order_items) AS total_revenue,
    (SELECT COUNT(*) FROM orders) AS total_orders,
    (SELECT COUNT(*) FROM customers) AS total_customers,
    (SELECT SUM(quantity * price_per_unit) / COUNT(DISTINCT order_id)
     FROM order_items) AS avg_order_value;

-- 70. Sales dashboard dataset (monthly)
SELECT 
    DATE_TRUNC('month', o.order_date) AS month,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.quantity * oi.price_per_unit) AS revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY month
ORDER BY month;






